volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: slavalyub/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media
      - ./data/:/prepared_data/

  frontend:
    container_name: foodgram_frontend
    image: slavalyub/foodgram_frontend
    command: sh -c "cp -r /app/build/. /static/"
    volumes:
      - static_volume:/static

  gateway:
    container_name: foodgram_proxy
    image: slavalyub/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 8003:80
    volumes:
      - media_volume:/media/
      - static_volume:/static/
