volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: slavalyub/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - ../data/:/prepared_data/
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/

  frontend:
    container_name: foodgram-front
    image: slavalyub/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/

  gateway:
    container_name: foodgram-proxy
    image: slavalyub/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 8003:80
    volumes:
      - foodgram_media:/media/
      - foodgram_static:/static/