# Generated by Django 4.2 on 2024-08-30 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_tag_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Введите уникальное имя пользователя.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='The field contains invalid characters. Only letters, spaces, and hyphens are allowed.', regex='[\\$\\%\\^\\&\\#\\:\\;!]')], verbose_name='Имя пользователя'),
        ),
    ]
