# Generated by Django 3.2 on 2024-08-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20240820_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
