# Generated by Django 3.2 on 2024-08-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('author', 'name')},
        ),
    ]
